<?php

namespace DoctrineProxies\__CG__\OrangeHRM\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PayrollConfiguration extends \OrangeHRM\Entity\PayrollConfiguration implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'OrangeHRM\\Entity\\PayrollConfiguration' . "\0" . 'id', '' . "\0" . 'OrangeHRM\\Entity\\PayrollConfiguration' . "\0" . 'pfEmployee', '' . "\0" . 'OrangeHRM\\Entity\\PayrollConfiguration' . "\0" . 'pfEmployer', '' . "\0" . 'OrangeHRM\\Entity\\PayrollConfiguration' . "\0" . 'esicEmployee', '' . "\0" . 'OrangeHRM\\Entity\\PayrollConfiguration' . "\0" . 'esicEmployer', '' . "\0" . 'OrangeHRM\\Entity\\PayrollConfiguration' . "\0" . 'gratuity', '' . "\0" . 'OrangeHRM\\Entity\\PayrollConfiguration' . "\0" . 'medical', '' . "\0" . 'OrangeHRM\\Entity\\PayrollConfiguration' . "\0" . 'epsContri', '' . "\0" . 'OrangeHRM\\Entity\\PayrollConfiguration' . "\0" . 'epsepfContri', '' . "\0" . 'OrangeHRM\\Entity\\PayrollConfiguration' . "\0" . 'tdsDedu'];
        }

        return ['__isInitialized__', '' . "\0" . 'OrangeHRM\\Entity\\PayrollConfiguration' . "\0" . 'id', '' . "\0" . 'OrangeHRM\\Entity\\PayrollConfiguration' . "\0" . 'pfEmployee', '' . "\0" . 'OrangeHRM\\Entity\\PayrollConfiguration' . "\0" . 'pfEmployer', '' . "\0" . 'OrangeHRM\\Entity\\PayrollConfiguration' . "\0" . 'esicEmployee', '' . "\0" . 'OrangeHRM\\Entity\\PayrollConfiguration' . "\0" . 'esicEmployer', '' . "\0" . 'OrangeHRM\\Entity\\PayrollConfiguration' . "\0" . 'gratuity', '' . "\0" . 'OrangeHRM\\Entity\\PayrollConfiguration' . "\0" . 'medical', '' . "\0" . 'OrangeHRM\\Entity\\PayrollConfiguration' . "\0" . 'epsContri', '' . "\0" . 'OrangeHRM\\Entity\\PayrollConfiguration' . "\0" . 'epsepfContri', '' . "\0" . 'OrangeHRM\\Entity\\PayrollConfiguration' . "\0" . 'tdsDedu'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (PayrollConfiguration $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId(int $id): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getPfEmployee(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPfEmployee', []);

        return parent::getPfEmployee();
    }

    /**
     * {@inheritDoc}
     */
    public function setPfEmployee(?float $pfEmployee): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPfEmployee', [$pfEmployee]);

        parent::setPfEmployee($pfEmployee);
    }

    /**
     * {@inheritDoc}
     */
    public function getPfEmployer(): float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPfEmployer', []);

        return parent::getPfEmployer();
    }

    /**
     * {@inheritDoc}
     */
    public function setPfEmployer(float $pfEmployer): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPfEmployer', [$pfEmployer]);

        parent::setPfEmployer($pfEmployer);
    }

    /**
     * {@inheritDoc}
     */
    public function getEsicEmployee(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEsicEmployee', []);

        return parent::getEsicEmployee();
    }

    /**
     * {@inheritDoc}
     */
    public function setEsicEmployee(?float $esicEmployee): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEsicEmployee', [$esicEmployee]);

        parent::setEsicEmployee($esicEmployee);
    }

    /**
     * {@inheritDoc}
     */
    public function getEsicEmployer(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEsicEmployer', []);

        return parent::getEsicEmployer();
    }

    /**
     * {@inheritDoc}
     */
    public function setEsicEmployer(?float $esicEmployer): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEsicEmployer', [$esicEmployer]);

        parent::setEsicEmployer($esicEmployer);
    }

    /**
     * {@inheritDoc}
     */
    public function getGratuity(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGratuity', []);

        return parent::getGratuity();
    }

    /**
     * {@inheritDoc}
     */
    public function setGratuity(?float $gratuity): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGratuity', [$gratuity]);

        parent::setGratuity($gratuity);
    }

    /**
     * {@inheritDoc}
     */
    public function getMedical(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMedical', []);

        return parent::getMedical();
    }

    /**
     * {@inheritDoc}
     */
    public function setMedical(?float $medical): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMedical', [$medical]);

        parent::setMedical($medical);
    }

    /**
     * {@inheritDoc}
     */
    public function getEpsContri(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEpsContri', []);

        return parent::getEpsContri();
    }

    /**
     * {@inheritDoc}
     */
    public function setEpsContri(?float $epsContri): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEpsContri', [$epsContri]);

        parent::setEpsContri($epsContri);
    }

    /**
     * {@inheritDoc}
     */
    public function getEpsepfContri(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEpsepfContri', []);

        return parent::getEpsepfContri();
    }

    /**
     * {@inheritDoc}
     */
    public function setEpsepfContri(?float $epsepfContri): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEpsepfContri', [$epsepfContri]);

        parent::setEpsepfContri($epsepfContri);
    }

    /**
     * {@inheritDoc}
     */
    public function getTdsDedu(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTdsDedu', []);

        return parent::getTdsDedu();
    }

    /**
     * {@inheritDoc}
     */
    public function setTdsDedu(?float $tdsDedu): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTdsDedu', [$tdsDedu]);

        parent::setTdsDedu($tdsDedu);
    }

}
